### ISSUE TITLE
sfdx sfpowerscripts:releasedefinition:generate does not commit the generated file.

### ISSUE THREAD

**Issue by Schuchie** [dxatscale/sfpowerscripts#1127]
**Describe the bug**
The sfdx sfpowerscripts:releasedefinition:generate command does not commit the generated file. This makes the command unusable in a CI-System.

**To Reproduce**

Run the following command:
`sfdx sfpowerscripts:releasedefinition:generate -n "test-release" -b "test-release"  -f ./release-definitions/release-config.yml -c origin/main`

with the following config
```
skipIfAlreadyInstalled: true
releasedefinitionProperties:
  changelog:
    workItemFilters: 
      -  WI-[0-9]{6}.*
    workItemUrl: https://jira.atlassian.net/browse
    limit: 30
```

The log itself shows that the branch got created and the generated file gets committed and pushed, but it doesn't.
Only the branch gets created with the no new commit.

**Expected behavior**
Release-branch with generated file gets created.

**Screenshots**
-

**Platform Details (please complete the following information):**
 - OS: ghcr.io/dxatscale/sfpowerscripts:19.4.1-2960727426
 - Version [e.g. CLI Version  eg: 1.6.6]: sfpowerscripts  -- The DX@Scale CI/CD Orchestrator -Version:19.4.1 -Release:August 22
 - Salesforce CLI(sfdx cli) Version:  7.160.0 
 - CI Platform: GitHub-Actions

**Additional context**
If you remove the following line, it works:
`sfpowerscripts/packages/sfpowerscripts-cli/src/impl/release/ReleaseDefinitionGenerator.ts:123`
```
        //git.checkout(this.gitRef, true);
```
