### ISSUE TITLE
feat: Config alternative for SFPOWERSCRIPTS_ARTIFACT_PACKAGE

### ISSUE THREAD

**Issue by attilah** [dxatscale/sfpowerscripts#1172]
**Describe the feature**
As an ISV we are having namespaced scratch orgs and to be able to utilize DX@Scale we had to adopt and create our own namespaced version of the artifact package.

Today the only way to specify an alternate package Id is using the `SFPOWERSCRIPTS_ARTIFACT_PACKAGE` environment variable.

**Proposal**

It would be nice to be able to specify this package Id in the extended `sfdx-project.json` or in the config file for the scratch org pools. I'd prefer the second version.

I'm willing to help and implement this feature if you agree it would be valuable.

**Comment by azlam-abdulsalam** [comment]
@attilah We have not considered the ISV scenarios yet. Happy to discuss further and how we could take these stories

**Comment by yippie** [comment]
The best option would be to simply make the included sfpowerscripts package namespaced. A namespaced package could be used in any and all orgs, eliminating the need for SFPOWERSCRIPTS_ARTIFACT_PACKAGE entirely.

**Comment by packocz** [comment]
@attilah did you manage to get Scratch Org Pools working with the custom namespaced version of the unlocked package? For me doing the below stops the error about installing Package without Namespace to a Namespaced Scratch Org, but then I still get errors about the package missing.

```
- name: Prepare a pool of scratch orgs
        env:
          SFPOWERSCRIPTS_ARTIFACT_PACKAGE: ${{ vars.SFPOWERSCRIPTS_ARTIFACT_PACKAGE }}
        run: sfp orchestrator:prepare -f ${POOL_DEF_FILE} -v devhub
```

> Unable to fetch any sfpowerscripts artifacts in the org
> 1. sfpowerscripts package is not installed in the org
> 2. The required prerequisite object is not deployed to this org
