### ISSUE TITLE
GitLab NPM Scope adds second @ in orchestrator:release

### ISSUE THREAD

**Issue by dschibster** [dxatscale/sfpowerscripts#1200]
**Describe the bug**
After checking at multiple junctures what the issue may be, I have come to the conclusion that the failure in our pipelines could only stem from the duplicate @ that is prepended to the npm_scope, because I could verify that the artifact exists, and at all other places I was not able to find any traces. #1168 already had such a failure, but only publish.ts was fixed as a hotfix. It seems more than publish is affected.

**To Reproduce**

* Update a Package using orchestrator:publish 
* Create a Pipeline for manual-release
* Run a Pipeline for Staging or whatever Instance is chosen as the first one.

**Expected behavior**

Artifacts should be found and released to target Instance

**Screenshots**

![image](https://user-images.githubusercontent.com/34553908/214070936-5f9ea6d3-0613-43ac-b300-195eb8e6310f.png)

**Platform Details (please complete the following information):**
 - OS: Using the Docker Image provided at ghcr.io/dxatscale/sfpowerscripts
 - Version [e.g. CLI Version  eg: 1.6.6]: 20.2.11
 - Salesforce CLI(sfdx cli) Version: 1.179,9
 - CI Platform: GitLab

**Additional context**
Probably a follow up issue to #1168 as more than one script uses npm scope in a similar way to `publish`. For me, it happens when running the `release` command.

**Comment by vuha-acn** [comment]
@dschibster - To fix the error, I have done the following in the in the default section:

1. Added the "@" manually in the writing of the .npmrc file at the top for default
2. Removed the "@" for the variable `--scope "$NPM_SCOPE"`

I'll be updated the dxatscale-templates soon to reflect this and corresponding documentation.

````
default:
   image: ghcr.io/dxatscale/sfpowerscripts
   # Generate NPM Configuration File for Package Registry Publishing
   before_script:
    - sfdx auth:sfdxurl:store -f "$DEVHUB_SFDX_AUTH_URL" -a "$DEVHUB_ALIAS"
    - echo "@${NPM_SCOPE}:registry=https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" >> .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc 
    # Below setting is required to push git tags and changelog to the repo      
    - git remote set-url --push origin https://gitlab-ci-token:${PROJECT_ACCESS_TOKEN}@$CI_SERVER_HOST/$CI_PROJECT_PATH.git
````
