### ISSUE TITLE
sfpowerscripts:releasedefinition:generate do not use flags from configfile

### ISSUE THREAD

**Issue by alanjaouen** [dxatscale/sfpowerscripts#1215]
**Describe the bug**
`promotePackagesBeforeDeploymentToOrg` is not written with `sfpowerscripts:releasedefinition:generate`

**To Reproduce**
with a release definition with:
```yaml
...
releasedefinitionProperties:
    skipIfAlreadyInstalled: true
    promotePackagesBeforeDeploymentToOrg: 'prod'
```
will not have the flag `promotePackagesBeforeDeploymentToOrg` on the generated release

**Expected behavior**
The value `promotePackagesBeforeDeploymentToOrg` should exist in the generated release file with the same value that the definition file

**Additional context**
when I looked at https://github.com/dxatscale/sfpowerscripts/blob/main/packages/sfpowerscripts-cli/src/impl/release/ReleaseDefinitionGenerator.ts#L165
I dont see any reference of this field, (and `skipIfAlreadyInstalled` seems to be hardcoded to `true`)
