### ISSUE TITLE
intall external Unlocked : multiple package with same begining

### ISSUE THREAD

**Issue by alanjaouen** [dxatscale/sfpowerscripts#1284]
**Describe the bug**

I have to external dependency:
- `"Nebula Logger Plugin - Slack@v1.5.2": "04t5Y0000015nDJQAY"`
- `"Nebula Logger@v4.9.11": "04t5Y0000015nDxQAI"`

only `"Nebula Logger@v4.9.11": "04t5Y0000015nDxQAI"` is installed on org.

When I install a release with the following definition

```yaml
...
packageDependencies:
    Nebula Logger Plugin - Slack@v1.5.2: 04t5Y0000015nDJQAY
    Nebula Logger@v4.9.11: 04t5Y0000015nDxQAI
...
```

package installation is skipped with message
```
  Checking whether package  Nebula Logger Plugin - Slack@v1.5.2 with ID 04t5Y0000015nDJQAYis installed in xxx@yyy.com
  Package to be installed was found in the target org xxx@yyy.com
  Skipping Installing of package Nebula Logger Plugin - Slack@v1.5.2 in xxx@yyy.com
```

but the package is not present in the org. Ending with a non installed package.

**To Reproduce**

- install 04t5Y0000015nDxQAI to an empty org
- release the file
```yaml
release: CRM_1.4.1
skipIfAlreadyInstalled: true
artifacts:
packageDependencies:
    Nebula Logger Plugin - Slack@v1.5.2: 04t5Y0000015nDJQAY
    Nebula Logger@v4.9.11: 04t5Y0000015nDxQAI
```

**Expected behavior**

`Nebula Logger@v4.9.11: 04t5Y0000015nDxQAI` should be skipped & `Nebula Logger Plugin - Slack@v1.5.2: 04t5Y0000015nDJQAY` installed.

**Additional context**

After looking at the code, it seems that #1245 added this behaviour
```shell
❯_ ❯  node
Welcome to Node.js v18.14.2.
Type ".help" for more information.
> a = '04t5Y0000015nDxQAI'
'04t5Y0000015nDxQAI'
> b = '04t5Y0000015nDJQAY'
'04t5Y0000015nDJQAY'
> a.substring(0,14) == b.substring(0,14)
true
```
