### ISSUE TITLE
 sfdx sfpowerscripts:orchestrator:validateAgainstOrg release config is ignored..

### ISSUE THREAD

**Issue by JoeffreyChaucer** [dxatscale/sfpowerscripts#1314]
**Describe the bug**
We are trying to do a daily validation to all our packages againts an empty sandboxOrg. Currently we are encountering error in one our package. We found out what was causing it. We needed src-env-specific-pre to deployed aswell but in our sfdx-project.json it is **ignoreOnStage - validate** . We tried using thorough-release-config with release-config file to include all packages..However src-env-specific-pre is still being ignore due to the **ignoreOnStage settings**.

**To Reproduce**
1. Create a new Prepare pipeline. Use releaseConfigFile parameter to validate the packages that you want:
```
skipIfAlreadyInstalled: true
excludeArtifacts:
  - src-temp
excludePackageDependencies:
  - Genesys Cloud for Salesforce
  - Marketing Cloud
releasedefinitionProperties:
 skipIfAlreadyInstalled: true
 changelog:
  workItemFilters:
    -  MUCRM-[0-9]{3,4}
    -  MCC-[0-9]{3,4}
  workItemUrl: https://johndoe.atlassian.net/browse
  limit: 30
```
2. Add     `sfdx sfpowerscripts:orchestrator:validateAgainstOrg -u integrationuser@test.com -g "---" --mode="thorough-release-config" --disablesourcepkgoverride  --devhubalias devhub  --disableparalleltesting --releaseconfig=release-config/release-defn.yml`
3. Run pipeline

**Expected behavior**
The `thorough-release-config`  with `release-config-file` mode in  `sfdx sfpowerscripts:orchestrator:validateAgainstOrg` should override the sfdx-project.json ignoreOnStage setting.

**Screenshots**
![image](https://github.com/dxatscale/sfpowerscripts/assets/48306432/ca837945-081a-4804-b975-d5e6abecc575)

![image](https://github.com/dxatscale/sfpowerscripts/assets/48306432/de69d373-7263-4f85-855b-f801e9e0f98e)
![image](https://github.com/dxatscale/sfpowerscripts/assets/48306432/3b45f680-240d-4d4b-b098-19bc7f0f550d)

**After Removing ignoreOnStage validate in the pre packages**
![image](https://github.com/dxatscale/sfpowerscripts/assets/48306432/9d6ceaee-3d60-470a-9a12-e4c2b343e781)

**Platform Details (please complete the following information):**
 - OS: Linux
 - Version [e.g. CLI Version  eg: 1.6.6] LATEST (20.26.3)
 - Salesforce CLI(sfdx cli) Version:  7.186.2
 - CI Platform: Buildkite

**Additional context**
Also I tried removing the **ignoreOnStage - validate**, I also encountered a new problem the package creation for the **pre** packages are failing.
