### ISSUE TITLE
PMD Analysis - Cannot Export Full HTML Scan Results

### ISSUE THREAD

**Issue by pb-seiso** [dxatscale/sfpowerscripts#145]
I'm currently experiencing an issue in which I can't seem to export PMD scan results as the specified format or file name based on the `format` and `outputPath` task variables. The published artifact containing all the results defaults to "sf-pmd-output.xml".

Running in ADO Classic, my YAML equivalent is:
```
steps:
- task: AzlamSalam.sfpowerscripts.sfpwowerscripts-analyzewithpmd-task.sfpwowerscripts-analyzewithpmd-task@7
  displayName: 'Analyze ''source/xyz'' using PMD'
  inputs:
    directory: '''source/xyz''
    outputPath: '$(Agent.BuildDirectory)/pmd_results'
```

Then I publish the file specified by `outputPath`:

```
steps:
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: pmd_results'
  inputs:
    ArtifactName: 'pmd_results'
``` 

I see the HTML get generated in the console, but not published to my artifacts. Instead, a directory is created that matches my `outputPath` "pmd_results", and only publishes a single Markdown file ".codeAnalysis/CodeAnalysisBuildSummary.md".

```
PMD found 2993 violations in 183 files with 45 critical defects
```

How can I export the full HTML results?

**Comment by Caitlyn-Mills** [comment]
Hi,

As per the example [here](https://dxatscale.gitbook.io/sfpowerscripts/azure-pipelines/task-specifications/testing-tasks/run-a-static-analysis-of-apex-classes-with-pmd) you will need to set your format to **html**. 
Navigate to the 'YAML example' tab under parameters to see an example. 

Caitlyn

**Comment by Caitlyn-Mills** [comment]
Hi, 

Can you please try following the example [here](https://dxatscale.gitbook.io/sfpowerscripts/azure-pipelines/task-specifications/testing-tasks/run-a-static-analysis-of-apex-classes-with-pmd) under 'Parameters' > 'Yaml Example'. 

Caitlyn

**Comment by vuha-acn** [comment]
Another temporary workaround that I've been using is to run it via the CLI and plugin [sfpowerkit](https://github.com/Accenture/sfpowerkit#sfpowerkitsourcepmd) to generate a CSV of the PMD results.

**Comment by azlam-abdulsalam** [comment]
We will be in exposing the artifact file path in the upcoming release. Stay Tuned!

**Comment by pb-seiso** [comment]
@Caitlyn-Mills As I don't have a custom ruleset, I don't know if that example will work. I tried this more explicit YAML with the sfpowerkit ruleset. It produced the same results as in my original post.

```
- task: sfpwowerscripts-analyzewithpmd-task@7
  displayName: Run PMD Static Code Analysis
  inputs:
    project_directory:
    directory: 'sfdx-source/xyz'
    ruleset: sfpowerkit
    format: 'html'
    outputPath: 'pmd_results.html'
```

@azlam-abdulsalam Excellent, I'll keep an eye out for the update. Thanks!
