### ISSUE TITLE
sfpwowerscripts-analyzewithpmd-task not using custom pmd-ruleset.xml

### ISSUE THREAD

**Issue by kaboomkazoom** [dxatscale/sfpowerscripts#304]
Not able to use a custom pmd-ruleset.xml file with sfpwowerscripts-analyzewithpmd-task (Version 8.0.5)

The following YAML
```
steps:
- task: AzlamSalam.sfpowerscripts.sfpwowerscripts-analyzewithpmd-task.sfpwowerscripts-analyzewithpmd-task@8
  displayName: 'Analyze Apex using PMD'
  inputs:
    directory: 'force-app-package_src_delta/force-app'
    ruleset: Custom
    rulesetpath: 'pmd-ruleset.xml'
    version: '6.26.0'
    isToBreakBuild: true
```

Generates the following command without any reference to pmd-ruleset.xml
```
    npx sfdx sfpowerkit:source:pmd -d  force-app-package_src_delta/force-app -f  text --version=6.26.0 --loglevel INFO
```
