### ISSUE TITLE
Moving from Azure pipeline tasks to the sfpowerscripts CLI - Delta packages

### ISSUE THREAD

**Issue by extravio** [dxatscale/sfpowerscripts#762]
Hi @azlam-abdulsalam , 

Our organisation has been using the Azure pipelines tasks for quite a while and we're looking at migrating to the sfpowerscripts CLI because the  sfpwowerscript-installsfdx-task is now randomly failing :
![image](https://user-images.githubusercontent.com/1171158/142291677-74bed729-e96a-4cb2-8484-760e30543422.png)
```
- task: sfpwowerscript-installsfdx-task@7
  displayName: Install SFDX
  inputs: 
    sfdx_cli_version: 7.110.0
    sfpowerkit_version: 2.9.2
```

Anyway, we have legacy Orgs that are not using packages.
I suppose migrating the "sfpwowerscripts-createsourcepackage-task@12"  to "[sfdx sfpowerscripts:package:source:create](https://github.com/Accenture/sfpowerscripts/tree/develop/packages/sfpowerscripts-cli#sfdx-sfpowerscriptspackagesourcecreate)" should be pretty straightforward.
However, we have a couple of Orgs that are using the "Delta package" task "sfpwowerscripts-createdeltapackage-task@6".
Is there a way of doing a similar thing with the new version of "sfpowerscripts-cli"?

Using the "--diffcheck " argument in [sfdx sfpowerscripts:package:source:create](https://github.com/Accenture/sfpowerscripts/tree/develop/packages/sfpowerscripts-cli#sfdx-sfpowerscriptspackagesourcecreate)
still builds the whole thing, is it correct?
